### ISSUE TITLE
one-way hashing algorithm

### ISSUE THREAD

**Issue by RootUp** [nmap/ncrack#40]
Hi Team, 

This issue was observed during source code analysis, we saw that:
`https://github.com/nmap/ncrack/blob/master/opensshlib/defines.h#L691`

The crypt functions use a poor one-way hashing algorithm; since they only accept passwords of 8 characters or fewer and only a two-byte salt, they are excessively vulnerable to dictionary attacks given today's faster computing equipment such as (CWE-327). 

It is recommended to use a different algorithm, such as SHA-256, with a larger, non-repeating salt.

Cheers!

**Comment by dmiller-nmap** [comment]
Thanks for your concern. This line is

1. in a 3rd-party library included in our source,
2. only enabled for LynxOS, an uncommon RTOS last released in 2013 and not officially supported by our software,
3. in a software package specifically designed for breaking security schemes.

Nmap Project software often includes implementations of weak authentication and encryption in order to be compatible with those schemes where they are used in target networks. Replacing these implementations with different ones is antithetical to the purpose of our software.
